### ISSUE TITLE
it doesn`t work

### ISSUE THREAD

**Issue by jyf007** [tiansh/us-else#1]
i had already installed user Script
i can`t open the zhihu site in 2016 feb 15th.
here is the snapshot
![zhihu](https://cloud.githubusercontent.com/assets/17245835/13042325/3436d0dc-d3fa-11e5-83f8-dfa71c7c9013.PNG)

**Comment by tiansh** [comment]
If you mean the script Zhihu Visitor (知乎免登录), it only works on question pages such as http://www.zhihu.com/question/22542607 . The script helps you that you can click more button on question pages without login. But this script do not modify home page. It is designed like this.
Check out the script description on script [home page](https://tiansh.github.io/us-else/zhihu_visitor/) for more details.

If you are redirected from question page, please leave the original URL in the comment. So I can check what goes wrong.

**Comment by jyf007** [comment]
抱歉，我发现晚了
