### ISSUE TITLE
知乎免登录#失效

### ISSUE THREAD

**Issue by mzhboy** [tiansh/us-else#3]
**脚本名称**:
知乎免登录
**问题描述**:
失效啦！

**Comment by tiansh** [comment]
我这正常。

如果你那有问题，请给了链接和运行环境，谢谢。

**Comment by mzhboy** [comment]
chrome 版本 54.0.2840.99 m (64-bit)，sc电信
用隐身模式，仅开tampermonkey和Chrono
其中tampermonkey只打开Zhihu Visitor
用后面的 [链接](https://www.zhihu.com/question/53686737)
结果如下图，这样的现象有几天了
![folded](https://cloud.githubusercontent.com/assets/5281193/21291701/d3cbbdda-c524-11e6-93ed-420db1a7fcd0.JPG)

**Comment by tiansh** [comment]
我这即便不用样式也看不到这个效果……

**Comment by mzhboy** [comment]
刚刚用ie试了，就这效果

PS：没有登陆

**Comment by mzhboy** [comment]
用ublock origin 查看script

![script](https://cloud.githubusercontent.com/assets/5281193/21291843/567c8a12-c529-11e6-8c43-09403b1dfdcb.JPG)

**Comment by dl0224** [comment]
firefox esr上也失效，不过好像是版本的关系
用虚拟机试了下，esr到45.3版本就失效了，45版本还能正常使用，希望大神有空修复一下

**Comment by mzhboy** [comment]
疑似脚本间的冲突，删掉部分，重启后没问题了
