### ISSUE TITLE
现在已经失效了，点击查看更多，会显示不允许点击的图标。

### ISSUE THREAD

**Issue by hou-solifugus** [tiansh/us-else#4]
**脚本名称**:
知乎免登录
**问题描述**:
现在已经失效了，点击查看更多，会显示不允许点击的图标。

**Comment by marvinbin121** [comment]
我试没找到问题下的更多回答的问题，反正https://www.zhihu.com/explore#monthly-hot热门搜索目录下的更多点击后无效且光标会变成禁止符号。

**Comment by tiansh** [comment]
才发现 oujs 上忘记删掉了，现在删掉了（三年后）
