### ISSUE TITLE
Zhihu Visitor脚本失效

### ISSUE THREAD

**Issue by TinaryTree** [tiansh/us-else#5]
**脚本名称**:
Zhihu Visitor
**问题描述**:
您好，看起来是知乎页面改版了，导致现在的脚本失效了。希望能做一下更新~

**Comment by tiansh** [comment]
这脚本很久没更新了，也不打算继续维护了。应该早就出问题了。

**Comment by tiansh** [comment]
啊，发现oujs 上忘记删掉了，现在删掉了。

**Comment by e71828** [comment]
凉凉
